export const enum Getters {
    GET_FIRST_NAME = 'GET_FIRST_NAME',
    GET_LAST_NAME = 'GET_LAST_NAME',
    GET_PHONE_NUMBER = 'GET_PHONE_NUMBER'
}

export const enum Actions {
    SET_FIRST_NAME = 'SET_FIRST_NAME',
    SET_LAST_NAME = 'SET_LAST_NAME',
    SET_PHONE_NUMBER = 'SET_PHONE_NUMBER'
}

export const enum Mutations {
    MUTATE_FIRST_NAME = 'MUTATE_FIRST_NAME',
    MUTATE_LAST_NAME= 'MUTATE_LAST_NAME',
    MUTATE_PHONE_NUMBER = 'MUTATE_PHONE_NUMBER'
}
